### ISSUE TITLE
Does this app support the Github 2FA?

### ISSUE THREAD

**Issue by SeppPenner** [privacyidea/privacyidea-authenticator#93] opened 2020-02-27 08:21 UTC
Just a small question: Does this app support the Github 2FA and if yes how can I set it up? :) I had some trouble just scanning the QR code.

**Comment by nilsbehlen** [comment] 2020-02-27 09:42
Hi, thanks for pointing this out!
The problem is that Github does not use uppercase letters for the Base32 secret, which is then not recognized by the decoder. The fix will be included in the next version.
As a workaround, you could add the token manually using the uppercase letters.

**Comment by SeppPenner** [comment] 2020-02-27 10:12
Nice, thank you for the quick reply :)

**Comment by nilsbehlen** [comment] 2020-03-12 12:14
###

**Closed by nilsbehlen** 2020-03-12 12:14 UTC
